general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
WINIT_UNIX_BACKEND = "wayland"

[window]
decorations = "None"
padding = { x = 10, y = 10 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "SemiBold" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "SemiBold Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 13.0

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true

[mouse]
hide_when_typing = true

