general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
padding = { x = 10, y = 0 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "SemiBold" }
size = 13.0

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
]

